### PR TITLE
Fixes download error 'No such file or directory' when transferMode = .largeData

### PR DESCRIPTION
**Pull request by Kondamon**
When transferMode = .largeData the data is downloaded to a temporary file in `Downloads` folder. However, when the `Downloads` folder does not yet exists the following error is shown:

2022-06-01 09:01:04.079666+0200 Project[3490:61771] open on .../Library/Developer/CoreSimulator/Devices/0FAC81F6-4CC8-492C-AB90-BD7A148107C9/data/Containers/Data/Application/9BE2AA69-AFBB-4796-90A0-9BAC0CE7CCE3/Downloads/ACEC951C-84BC-44E4-8B27-0B6BC2623240: No such file or directory

The pull requests resolves the issue and creates the temporary folder if it does'n yet exists.

### CODE REVIEW

**Comment by Kondamon** [comment]
Perhaps another test where the downloads folder is deleted and the automatically recreated should be added since it seems like that on the CI the `Downloads` folder always exists. (But not in Simulators with Xcode Version 13.4 (13F17a))

**Comment by Kondamon** [comment]
> Perhaps another test where the downloads folder is deleted and then automatically recreated should be added since it seems like that on the CI the `Downloads` folder always exists. (But not in Simulators with Xcode Version 13.4 (13F17a))

Done.

**Comment by erdemildiz-loodos** [comment]
I used like that worked fine
`downloadsDirectory` -> `documentDirectory`
```swift

extension FileManager {
    
    internal func temporaryFileLocation() -> URL {
        let fileName = UUID().uuidString
        let documentsDir = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first! as NSString
        let destinationURL = URL(fileURLWithPath: documentsDir.appendingPathComponent(fileName))
        return destinationURL
    }
    
}
```

**Comment by erdemildiz-loodos** [comment]
@malcommac Could you merge this changes

**Comment by Kondamon** [comment]
> I used like that worked fine
> `downloadsDirectory` -> `documentDirectory`

This would be another workaround. A temporary folder would have the benefit that it's cleaned automatically by the system (if needed). Anyway, the manual file handling is recommended by apple so the exact folder doesn't have a big impact.

**Pull request merged**
